@baseUrl = http://localhost:3000/api/v1

### Get all products
GET {{baseUrl}}/products

### Get a product by ID
GET {{baseUrl}}/products/83d87571-c020-4a20-a699-68411587cc14

### Create a new product
POST {{baseUrl}}/products
Content-Type: application/json

{
  "name": "Secundary Product",
  "price": 29.99
}

### Update a product by ID
PATCH {{baseUrl}}/products/b52fe308-997c-41d4-8096-099f2d1f2870
Content-Type: application/json

{
  "name": "Terceiro Product",
  "price": 29.99
}

### Delete a product by ID
DELETE {{baseUrl}}/products/b52fe308-997c-41d4-8096-099f2d1f2870